package org.firstinspires.ftc.teamcode.Utility;

import org.firstinspires.ftc.robotcore.external.Telemetry;

public class TelemetryTools {

    public static String setFontColor(String color, String text) {
        return "<font color=\""+color+"\">"+text+"</font>";
    }

    public static String setHeader(int headerNumber, String text) {
        return "<h"+headerNumber+">"+text+"</h"+headerNumber+">";
    }

    /**
     * Dear god do I have too much time......
     *     Current working colors:
     *
     *     Red
     *     Yellow
     *     Fuchsia / Magenta
     *     Purple
     *     Lime
     *     Green
     *     Olive
     *     Teal
     *     Aqua / Cyan
     *     Blue
     *     Navy
     *     Maroon
     *     White
     *     LightGray / Silver
     *     DarkGray
     *     Gray
     */
    public void DisplayAllHTMLNameColors(Telemetry telemetry) {
        StringBuilder builder = new StringBuilder();
        builder.append(TelemetryTools.setHeader(1, "Colors"))
                .append(TelemetryTools.setFontColor("INDIANRED", "INDIANRED"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LIGHTCORAL", "LIGHTCORAL"))
                .append("\n")
                .append(TelemetryTools.setFontColor("SALMON", "SALMON"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DARKSALMON", "DARKSALMON"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LIGHTSALMON", "LIGHTSALMON"))
                .append("\n")
                .append(TelemetryTools.setFontColor("CRIMSON", "CRIMSON"))
                .append("\n")
                .append(TelemetryTools.setFontColor("RED", "RED"))
                .append("\n")
                .append(TelemetryTools.setFontColor("FIREBRICK", "FIREBRICK"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DARKRED", "DARKRED"))
                .append("\n")
                .append(TelemetryTools.setFontColor("PINK", "PINK"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LIGHTPINK", "LIGHTPINK"))
                .append("\n")
                .append(TelemetryTools.setFontColor("HOTPINK", "HOTPINK"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DEEPPINK", "DEEPPINK"))
                .append("\n")
                .append(TelemetryTools.setFontColor("MEDIUMVIOLETRED", "MEDIUMVIOLETRED"))
                .append("\n")
                .append(TelemetryTools.setFontColor("PALEVIOLETRED", "PALEVIOLETRED"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LIGHTSALMON", "LIGHTSALMON"))
                .append("\n")
                .append(TelemetryTools.setFontColor("CORAL", "CORAL"))
                .append("\n")
                .append(TelemetryTools.setFontColor("TOMATO", "TOMATO"))
                .append("\n")
                .append(TelemetryTools.setFontColor("ORANGERED", "ORANGERED"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DARKORANGE", "DARKORANGE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("ORANGE", "ORANGE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("GOLD", "GOLD"))
                .append("\n")
                .append(TelemetryTools.setFontColor("YELLOW", "YELLOW"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LIGHTYELLOW", "LIGHTYELLOW"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LEMONCHIFFON", "LEMONCHIFFON"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LIGHTGOLDENRODYELLOW", "LIGHTGOLDENRODYELLOW"))
                .append("\n")
                .append("\n")
                .append(TelemetryTools.setFontColor("PAPAYAWHIP", "PAPAYAWHIP"))
                .append("\n")
                .append("\n")
                .append(TelemetryTools.setFontColor("MOCCASIN", "MOCCASIN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("PEACHPUFF", "PEACHPUFF"))
                .append("\n")
                .append(TelemetryTools.setFontColor("PALEGOLDENROD", "PALEGOLDENROD"))
                .append("\n")
                .append(TelemetryTools.setFontColor("KHAKI", "KHAKI"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DARKKHAKI", "DARKKHAKI"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LAVENDER", "LAVENDER"))
                .append("\n")
                .append(TelemetryTools.setFontColor("THISTLE", "THISTLE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("PLUM", "PLUM"))
                .append("\n")
                .append(TelemetryTools.setFontColor("VIOLET", "VIOLET"))
                .append("\n")
                .append(TelemetryTools.setFontColor("ORCHID", "ORCHID"))
                .append("\n")
                .append(TelemetryTools.setFontColor("FUCHSIA", "FUCHSIA"))
                .append("\n")
                .append(TelemetryTools.setFontColor("MAGENTA", "MAGENTA"))
                .append("\n")
                .append(TelemetryTools.setFontColor("MEDIUMORCHID", "MEDIUMORCHID"))
                .append("\n")
                .append(TelemetryTools.setFontColor("MEDIUMPURPLE", "MEDIUMPURPLE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("REBECCAPURPLE", "REBECCAPURPLE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("BLUEVIOLET", "BLUEVIOLET"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DARKVIOLET", "DARKVIOLET"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DARKORCHID", "DARKORCHID"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DARKMAGENTA", "DARKMAGENTA"))
                .append("\n")
                .append(TelemetryTools.setFontColor("PURPLE", "PURPLE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("INDIGO", "INDIGO"))
                .append("\n")
                .append(TelemetryTools.setFontColor("SLATEBLUE", "SLATEBLUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DARKSLATEBLUE", "DARKSLATEBLUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("MEDIUMSLATEBLUE", "MEDIUMSLATEBLUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("GREENYELLOW", "GREENYELLOW"))
                .append("\n")
                .append(TelemetryTools.setFontColor("CHARTREUSE", "CHARTREUSE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LAWNGREEN", "LAWNGREEN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LIME", "LIME"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LIMEGREEN", "LIMEGREEN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("PALEGREEN", "PALEGREEN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LIGHTGREEN", "LIGHTGREEN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("MEDIUMSPRINGGREEN", "MEDIUMSPRINGGREEN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("SPRINGGREEN", "SPRINGGREEN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("MEDIUMSEAGREEN", "MEDIUMSEAGREEN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("SEAGREEN", "SEAGREEN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("FORESTGREEN", "FORESTGREEN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("GREEN", "GREEN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DARKGREEN", "DARKGREEN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("YELLOWGREEN", "YELLOWGREEN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("OLIVEDRAB", "OLIVEDRAB"))
                .append("\n")
                .append(TelemetryTools.setFontColor("OLIVE", "OLIVE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DARKOLIVEGREEN", "DARKOLIVEGREEN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("MEDIUMAQUAMARINE", "MEDIUMAQUAMARINE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DARKSEAGREEN", "DARKSEAGREEN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LIGHTSEAGREEN", "LIGHTSEAGREEN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DARKCYAN", "DARKCYAN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("TEAL", "TEAL"))
                .append("\n")
                .append(TelemetryTools.setFontColor("AQUA", "AQUA"))
                .append("\n")
                .append(TelemetryTools.setFontColor("CYAN", "CYAN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LIGHTCYAN", "LIGHTCYAN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("PALETURQUOISE", "PALETURQUOISE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("AQUAMARINE", "AQUAMARINE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("TURQUOISE", "TURQUOISE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("MEDIUMTURQUOISE", "MEDIUMTURQUOISE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DARKTURQUOISE", "DARKTURQUOISE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("CADETBLUE", "CADETBLUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("STEELBLUE", "STEELBLUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LIGHTSTEELBLUE", "LIGHTSTEELBLUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("POWDERBLUE", "POWDERBLUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LIGHTBLUE", "LIGHTBLUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("SKYBLUE", "SKYBLUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LIGHTSKYBLUE", "LIGHTSKYBLUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DEEPSKYBLUE", "DEEPSKYBLUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DODGERBLUE", "DODGERBLUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("CORNFLOWERBLUE", "CORNFLOWERBLUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("MEDIUMSLATEBLUE", "MEDIUMSLATEBLUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("ROYALBLUE", "ROYALBLUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("BLUE", "BLUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("MEDIUMBLUE", "MEDIUMBLUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DARKBLUE", "DARKBLUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("NAVY", "NAVY"))
                .append("\n")
                .append(TelemetryTools.setFontColor("MIDNIGHTBLUE", "MIDNIGHTBLUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("CORNSILK", "CORNSILK"))
                .append("\n")
                .append(TelemetryTools.setFontColor("BLANCHEDALMOND", "BLANCHEDALMOND"))
                .append("\n")
                .append(TelemetryTools.setFontColor("BISQUE", "BISQUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("NAVAJOWHITE", "NAVAJOWHITE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("WHEAT", "WHEAT"))
                .append("\n")
                .append(TelemetryTools.setFontColor("BURLYWOOD", "BURLYWOOD"))
                .append("\n")
                .append(TelemetryTools.setFontColor("TAN", "TAN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("ROSYBROWN", "ROSYBROWN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("SANDYBROWN", "SANDYBROWN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("GOLDENROD", "GOLDENROD"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DARKGOLDENROD", "DARKGOLDENROD"))
                .append("\n")
                .append(TelemetryTools.setFontColor("PERU", "PERU"))
                .append("\n")
                .append(TelemetryTools.setFontColor("CHOCOLATE", "CHOCOLATE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("SADDLEBROWN", "SADDLEBROWN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("SIENNA", "SIENNA"))
                .append("\n")
                .append(TelemetryTools.setFontColor("BROWN", "BROWN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("MAROON", "MAROON"))
                .append("\n")
                .append(TelemetryTools.setFontColor("WHITE", "WHITE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("SNOW", "SNOW"))
                .append("\n")
                .append(TelemetryTools.setFontColor("HONEYDEW", "HONEYDEW"))
                .append("\n")
                .append(TelemetryTools.setFontColor("MINTCREAM", "MINTCREAM"))
                .append("\n")
                .append(TelemetryTools.setFontColor("AZURE", "AZURE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("ALICEBLUE", "ALICEBLUE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("GHOSTWHITE", "GHOSTWHITE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("WHITESMOKE", "WHITESMOKE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("SEASHELL", "SEASHELL"))
                .append("\n")
                .append(TelemetryTools.setFontColor("BEIGE", "BEIGE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("OLDLACE", "OLDLACE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("FLORALWHITE", "FLORALWHITE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("IVORY", "IVORY"))
                .append("\n")
                .append(TelemetryTools.setFontColor("ANTIQUEWHITE", "ANTIQUEWHITE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LINEN", "LINEN"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LAVENDERBLUSH", "LAVENDERBLUSH"))
                .append("\n")
                .append(TelemetryTools.setFontColor("MISTYROSE", "MISTYROSE"))
                .append("\n")
                .append(TelemetryTools.setFontColor("GAINSBORO", "GAINSBORO"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LIGHTGRAY", "LIGHTGRAY"))
                .append("\n")
                .append(TelemetryTools.setFontColor("SILVER", "SILVER"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DARKGRAY", "DARKGRAY"))
                .append("\n")
                .append(TelemetryTools.setFontColor("GRAY", "GRAY"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DIMGRAY", "DIMGRAY"))
                .append("\n")
                .append(TelemetryTools.setFontColor("LIGHTSLATEGRAY", "LIGHTSLATEGRAY"))
                .append("\n")
                .append(TelemetryTools.setFontColor("SLATEGRAY", "SLATEGRAY"))
                .append("\n")
                .append(TelemetryTools.setFontColor("DARKSLATEGRAY", "DARKSLATEGRAY"))
                .append("\n")
                .append(TelemetryTools.setFontColor("BLACK", "BLACK"));
        telemetry.addLine(builder.toString());
    }
}
